apiVersion: v1
kind: Service
metadata:
  name: devops-jedi-compendium
spec:
  type: ClusterIP
  selector:
    app: devops-jedi-compendium
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
